version: '3'
services:
    geoserver:
        image: quay.io/geomesa/geoserver:geomesa-1.3.2-accumulo-1.7.3
        ports:
          - 9090:9090
    hdfs-name:
        image: quay.io/geomesa/hdfs:geomesa-1.3.2-accumulo-1.7.3
        command: name
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
        ports:
          - 50070:50070
    hdfs-data:
        image: quay.io/geomesa/hdfs:geomesa-1.3.2-accumulo-1.7.3
        command: data
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
        depends_on:
          - hdfs-name
    zookeeper:
        image: quay.io/geomesa/zookeeper:latest
        ports:
          - 2181:2181
    accumulo-master:
      image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.7.3
      command: master --auto-init
      environment:
        HADOOP_MASTER_ADDRESS: hdfs-name
        ZOOKEEPERS: zookeeper
        ACCUMULO_PASSWORD: GisPwd
      depends_on:
        - zookeeper
      volumes:
        - ~/dev/ec4geomesa/:/data
    accumulo-monitor:
        image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.7.3
        command: monitor
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
          ZOOKEEPERS: zookeeper
        ports:
          - 9995:9995
          - 50095:50095
        depends_on:
          - zookeeper
          - accumulo-master
    accumulo-tserver:
        image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.7.3
        command: tserver
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
          ZOOKEEPERS: zookeeper
        depends_on:
          - zookeeper
          - accumulo-master
    
#    spark-master:
#        image: quay.io/geodocker/spark:latest
#        command: master
#        ports:
#          - 4040:4040
#          - 8080:8080
#        depends_on:
#          - zookeeper
#          - accumulo-master
#        volumes:
#         - ~/dev/geomesa/geomesa-tutorials/geomesa-examples-spark/target/:/target_examples
#    spark-worker:
#        image: quay.io/geodocker/spark:latest
#        command: worker
#        environment:
#          SPARK_MASTER: spark-master
#        depends_on:
#          - spark-master  
